apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-data
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 500G
  nfs:
    path: /srv/vols/gitea
    server: veo1.krft
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data
  namespace: gitea
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500G
  storageClassName: ""
  volumeName: gitea-data
