apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile
  namespace: k8plex-test
  labels:
    app: seafile
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: seafile
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: seafile
    spec: 
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "memcached"
      containers: 
      - image: mariadb:10.5
        name: seafile-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "ohTh6we9ong1almaFa"
        - name: MYSQL_LOG_CONSOLE
          value: "true"
        volumeMounts:
        - name: seafile-data
          mountPath: /var/lib/mysql/
          subPath: db
      - image: memcached:1.5.6
        name: seafile-memcached
        command: ["memcached"]
        args: ["-m 256"]
      - image: seafileltd/seafile-mc:9.0.2
        name: seafile
        env:
        - name: DB_HOST
          #value: "seafile-mysql"
          value: "127.0.0.1"
        - name: DB_ROOT_PASSWD
          value: "ohTh6we9ong1almaFa"
        - name: SEAFILE_ADMIN_EMAIL
          value: "kooplex@elte.hu"
        - name: SEAFILE_ADMIN_PASSWORD
          value: "Cut3chohSiealmafa"
        - name: SEAFILE_SERVER_LETSENCRYPT
          value: "false"
        - name: SEAFILE_SERVER_HOSTNAME
          value: "k8plex-test.vo.elte.hu"
        volumeMounts:
        - name: seafile-data
          mountPath: /shared/
          subPath: data
        ports:
        - containerPort: 80
        #- containerPort: 8082
      volumes:
        - name: seafile-data
          persistentVolumeClaim:
            claimName: seafile-data
---
apiVersion: v1
kind: Service
metadata:
  name: seafile
  namespace: k8plex-test
spec:
  ports:
  - name: seahub
    port: 80
    targetPort: 80
  #- name: seafhttp
  #  port: 8082
  #  targetPort: 8082
  selector:
    app: seafile
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seafile
  namespace: k8plex-test
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    #nginx.ingress.kubernetes.io/configuration-snippet: |
    #  proxy_set_header Host $host;
    #  proxy_set_header X-Real-IP $remote_addr;
    #  proxy_set_header X-Forwarded-For $remote_addr;
    #  proxy_set_header X-Forwarded-Host $server_name;
spec:
  rules:
  - host: k8plex-test.vo.elte.hu
    http:
      paths:
      - path: /seafile
        backend:
          service: 
            name: seafile
            port: 
              number: 80
        pathType: Prefix
      #- path: /seafhttp
      #  backend:
      #    service: 
      #      name: seafile
      #      port: 
      #        number: 8082
      #  pathType: Prefix
  tls:
  - hosts:
    - k8plex-test.vo.elte.hu
    secretName: k8plex-test-tls
