# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
FROM jupyter/scipy-notebook

MAINTAINER Jupyter Project <jupyter@googlegroups.com>

#USER root
RUN pip install --upgrade pip

RUN echo "deb http://archive.ubuntu.com/ubuntu jessie main" > /etc/apt/sources.list
RUN echo "deb http://archive.ubuntu.com/ubuntu jessie-updates main" >> /etc/apt/sources.list
RUN echo "deb http://ftp.us.debian.org/debian stable main contrib non-free" >> /etc/apt/sources.list
RUN apt-get update; exit 0
RUN apt-get install -y nodejs
RUN apt-get install -y npm
RUN npm install -g bower

#USER jovyan
#RUN mkdir -p /home/jovyan/.local/share        
#RUN mkdir -p /home/jovyan/.local/share/jupyter
RUN pip install https://github.com/ipython-contrib/IPython-notebook-extensions/archive/master.zip 

# install the python package
RUN pip install --upgrade jupyter_dashboards

# Install all parts of the extension to the active conda / venv / python env
# and enable all parts of it in the jupyter profile in that environment
# See jupyter dashboards quick-setup --help for other options (e.g., --user)
RUN jupyter dashboards quick-setup #--user
#RUN jupyter dashboards activate

# Install dashboard layout and preview within Jupyter Notebook
RUN pip   install jupyter_dashboards_bundlers

# Install all parts of the extension to the active conda / venv / python env
# and enable all parts of it in the jupyter profile in that environment
# See jupyter dashboards_bundlers quick-setup --help for other options (e.g., --user)
RUN jupyter dashboards_bundlers quick-setup #--user 

# install the python package
RUN pip install --upgrade jupyter_declarativewidgets

# Install all parts of the extension to the active conda / venv / python env
# and enable all parts of it in the jupyter profile in that environment
# See jupyter declarativewidgets quick-setup --help for other options (e.g., --user)
RUN jupyter declarativewidgets quick-setup #--user 
# The above command is equivalent to this sequence of commands:
# jupyter serverextension enable --py declarativewidgets --sys-prefix
# jupyter nbextension install --py declarativewidgets --sys-prefix
# jupyter nbextension enable --py declarativewidgets --sys-prefix

# Install content management to support dashboard bundler options
RUN pip install jupyter_cms
# Install all parts of the extension to the active conda / venv / python env
# and enable all parts of it in the jupyter profile in that environment
# See jupyter cms quick-setup --help for other options (e.g., --user)
RUN jupyter cms quick-setup #--user 

# Add local files as late as possible to avoid cache busting
ADD start-notebook.sh /usr/local/bin/start-notebook.sh
ADD start-singleuser.sh /usr/local/bin/start-singleuser.sh
