# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# Pin to a known release for sanity
FROM jupyter/pyspark-notebook:8015c88c4b11

# Become root to do the apt-gets
#USER root

RUN apt-get update && \
                apt-get install -y curl && \
                curl --silent --location https://deb.nodesource.com/setup_0.12 | sudo bash - && \
                apt-get install --yes nodejs && \
                npm install -g bower



#USER root
RUN apt update
RUN apt install -y python3-pip liblapack-dev libblas-dev
RUN apt install -y gfortran libfreetype6* pkg-config


#RUN chown jovyan /home/jovyan/* -R

RUN pip3 install --upgrade pip
RUN pip3 install pandas  numpy  scipy  matplotlib seaborn plotly igraph bokeh lifelines
RUN pip install pandas numpy scipy matplotlib seaborn plotly igraph bokeh lifelines

# Do the pip installs as the unprivileged notebook user
#USER jovyan

# Install dashboard layout and preview within Jupyter Notebook
#ARG DASHBOARDS_VER
RUN pip install "jupyter_dashboards" && \
        jupyter dashboards quick-setup --sys-prefix

# Install declarative widgets for Jupyter Notebook
#ARG DECLWIDGETS_VER
RUN pip install "jupyter_declarativewidgets" && \
        jupyter declarativewidgets quick-setup --sys-prefix

# Install content management to support dashboard bundler options
#ARG CMS_VER
#ARG BUNDLER_VER
RUN pip install "jupyter_cms" && \
        jupyter cms quick-setup --sys-prefix
RUN pip install "jupyter_dashboards_bundlers" && \
        jupyter dashboards_bundlers quick-setup --sys-prefix

# Put a couple sample notebooks into the notebook server
#RUN wget -O $HOME/work/hello_world.ipynb https://gist.githubusercontent.com/parente/bd6789c4a3533fab8085/raw/c5a8e9be2213650332889178b15cf899a844694f/hello_world.ipynb
#RUN wget -O $HOME/work/meetup-streaming.ipynb https://raw.githubusercontent.com/jupyter-incubator/dashboards/master/etc/notebooks/stream_demo/meetup-streaming.ipynb

# Stay as jovyan in the newer docker stack images
# Add local files as late as possible to avoid cache busting
ADD start-notebook.sh /usr/local/bin/start-notebook.sh
ADD start-singleuser.sh /usr/local/bin/start-singleuser.sh
#RUN chmod 775 /usr/local/bin/start-notebook.sh /usr/local/bin/start-singleuser.sh


