#! /bin/bash

source lib.sh

USERNAME=$1
FIRSTNAME=$2
LASTNAME=$3
EMAIL=$4
UID=$5
PASS=$6

ldap_adduser $USERNAME $FIRSTNAME $LASTNAME $EMAIL $UID $PASS
gitlab_adduser $USERNAME $FIRSTNAME $LASTNAME $EMAIL $UID $PASS