# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# Pin to a known release for sanity
#FROM jupyter/pyspark-notebook:8015c88c4b11

FROM kooplex-base

# Become root to do the apt-gets
#USER root

RUN apt update && \
                apt install -y curl && \
                curl --silent --location https://deb.nodesource.com/setup_0.12 | sudo bash - && \
                apt install --yes nodejs npm && \
                npm install -g bower



#USER root
RUN apt update
RUN apt install -y python3-pip liblapack-dev libblas-dev
RUN apt install -y gfortran libfreetype6* pkg-config


#RUN chown jovyan /home/jovyan/* -R

RUN pip3 install --upgrade pip
RUN pip3 install pandas  numpy  scipy  matplotlib seaborn plotly igraph bokeh lifelines
RUN pip install pandas numpy scipy matplotlib seaborn plotly igraph bokeh lifelines

# TODO add jupyter stuff

# Configure environment
ENV CONDA_VER latest
ENV CONDA_DIR /opt/conda
ENV PATH $CONDA_DIR/bin:$PATH
ENV SHELL /bin/bash
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

# Create conda dir
RUN mkdir -p $CONDA_DIR

# Install conda
RUN cd /tmp && \
    mkdir -p $CONDA_DIR && \
    wget --quiet https://repo.continuum.io/miniconda/Miniconda3-$CONDA_VER-Linux-x86_64.sh && \
    # echo "9ea57c0fdf481acf89d816184f969b04bc44dea27b258c4e86b1e3a25ff26aa0 *Miniconda3-3.19.0-Linux-x86_64.sh" | sha256sum -c - && \
    /bin/bash Miniconda3-$CONDA_VER-Linux-x86_64.sh -f -b -p $CONDA_DIR && \
    rm Miniconda3-$CONDA_VER-Linux-x86_64.sh && \
    $CONDA_DIR/bin/conda install --quiet --yes conda && \
    $CONDA_DIR/bin/conda config --system --add channels conda-forge && \
    $CONDA_DIR/bin/conda install --quiet --yes 'notebook' && \
    $CONDA_DIR/bin/conda install --quiet --yes 'jupyter' && \
    $CONDA_DIR/bin/conda install --quiet --yes 'jupyterhub' && \
    $CONDA_DIR/bin/conda install --quiet --yes 'jupyter'

# Install Jupyter notebook
# RUN conda clean -tipsy


# Do the pip installs as the unprivileged notebook user

# Install dashboard layout and preview within Jupyter Notebook
#ARG DASHBOARDS_VER
RUN pip install "jupyter_dashboards" && \
        jupyter dashboards quick-setup --sys-prefix

RUN pip install --upgrade pip
RUN pip install pandas
# Install declarative widgets for Jupyter Notebook
#ARG DECLWIDGETS_VER
RUN pip install "jupyter_declarativewidgets" && \
        jupyter declarativewidgets quick-setup --sys-prefix

# Install content management to support dashboard bundler options
#ARG CMS_VER
#ARG BUNDLER_VER
RUN pip install "jupyter_cms" && \
        jupyter cms quick-setup --sys-prefix
RUN pip install "jupyter_dashboards_bundlers" && \
        jupyter dashboards_bundlers quick-setup --sys-prefix

# Put a couple sample notebooks into the notebook server
#RUN wget -O $HOME/work/hello_world.ipynb https://gist.githubusercontent.com/parente/bd6789c4a3533fab8085/raw/c5a8e9be2213650332889178b15cf899a844694f/hello_world.ipynb
#RUN wget -O $HOME/work/meetup-streaming.ipynb https://raw.githubusercontent.com/jupyter-incubator/dashboards/master/etc/notebooks/stream_demo/meetup-streaming.ipynb

RUN pip install matplotlib


# Stay as jovyan in the newer docker stack images
# Add local files as late as possible to avoid cache busting
ADD scripts/start-notebook.sh /usr/local/bin/start-notebook.sh
ADD scripts/start-singleuser.sh /usr/local/bin/start-singleuser.sh

#RUN chmod 775 /usr/local/bin/start-notebook.sh /usr/local/bin/start-singleuser.sh


