#!/usr/bin/env python
"""Extend regular notebook server to be aware of multiuser things."""

# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

from jinja2 import ChoiceLoader, FunctionLoader
from notebook.notebookapp import NotebookApp

edit_template = """
{% extends "templates/edit.html" %}
{% block meta %}
<style>
.navbar-header > a {
    padding-right:30px;
}
</style>
{% endblock %}
{% block logo %}
{% endblock %}
  {% block headercontainer %}

    <a href="/hub/notebooks" >
       <img src="/notebook/{{ containername }}/static/base/images/kooplex-logo.png" height="35px" style="padding-right: 30px;">
    </a>
    <a href="/notebook/gadmin-ccfsd-gadmin/tree">
       <img src="/notebook/{{ containername }}/static/base/images/logo.png?v=641991992878ee24c6f3826e81054a0f" alt="Jupyter Notebook" height="35px">
    </a>
    <ul class="nav navbar-nav navbar-right">
        <li><a href="#" class="navbar-brand" style="color: black;"> <strong>Project - {{ project_name }}</strong></a></li>
    </ul>
{% endblock %}
"""

terminal_template = """
{% extends "templates/terminal.html" %}
{% block meta %}
<style>
.navbar-header > a {
    padding-right:30px;
}
</style>
{% endblock %}
{% block logo %}
{% endblock %}
  {% block headercontainer %}

    <a href="/hub/notebooks" >
       <img src="/notebook/{{ containername }}/static/base/images/kooplex-logo.png" height="35px" style="padding-right: 30px;">
    </a>
    <a href="/notebook/gadmin-ccfsd-gadmin/tree">
       <img src="/notebook/{{ containername }}/static/base/images/logo.png?v=641991992878ee24c6f3826e81054a0f" alt="Jupyter Notebook" height="35px">
    </a>
    <ul class="nav navbar-nav navbar-right">
        <li><a href="#" class="navbar-brand" style="color: black;"> <strong>Project - {{ project_name }}</strong></a></li>
    </ul>
{% endblock %}
"""


tree_template = """
{% extends "templates/tree.html" %}
{% block meta %}
<style>
.navbar-header > a {
    padding-right:30px;
}
</style>
{% endblock %}
{% block logo %}
{% endblock %}
  {% block headercontainer %}

    <a href="/hub/notebooks" >
       <img src="/notebook/{{ containername }}/static/base/images/kooplex-logo.png" height="35px" style="padding-right: 30px;">
    </a>
    <a href="/notebook/gadmin-ccfsd-gadmin/tree">
       <img src="/notebook/{{ containername }}/static/base/images/logo.png?v=641991992878ee24c6f3826e81054a0f" alt="Jupyter Notebook" height="35px">
    </a>
    <ul class="nav navbar-nav navbar-right">
        <li><a href="#" class="navbar-brand" style="color: black;"> <strong>Project - {{ project_name }}</strong></a></li>
    </ul>
{% endblock %}

{% block login_widget %}

    <span id="login_widget">
        <a href="/notebook/{{ containername }}/lab"><button id="switch" class="btn btn-sm navbar-btn">Switch to JupyterLab</button></a>
    </span>

  {% endblock %}

"""

notebook_template = """
{% extends "templates/notebook.html" %}
{% block meta %}
<style>
.navbar-header > a {
    padding-right:30px;
}
</style>
{% endblock %}
{% block logo %}
{% endblock %}
  {% block headercontainer %}

<span id="save_widget" class="save_widget">
    <span id="notebook_name" class="filename"></span>
    <span class="checkpoint_status"></span>
    <span class="autosave_status"></span>
    <a href="/hub/notebooks">
       <img src="/notebook/{{ containername }}/static/base/images/kooplex-logo.png" height="35px" style="padding-left: 30px; padding-right: 30px;">
    </a>
    <a href="/notebook/gadmin-ccfsd-gadmin/tree">
       <img src="/notebook/{{ containername }}/static/base/images/logo.png?v=641991992878ee24c6f3826e81054a0f" alt="Jupyter Notebook" height="35px">
    </a>
</span>

<a href="#" class="navbar-brand" style="color: black;"> <strong>Project - {{ project_name }}</strong></a>
<span id="kernel_logo_widget">
  {% block kernel_logo_widget %}
  <img class="current_kernel_logo" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"/>
  {% endblock %}
</span>

  {% endblock %}

"""


class KooplexUserNotebookApp(NotebookApp):

      def patch_templates(self):
        import os

        # let us point to some crasy urls with the buttons
        # this illustrates the values of some internal url type strings
        env = self.web_app.settings['jinja2_env']
        env.globals['stop_link'] = 'http://www.google.com/'+self.base_url
        env.globals['commit_link'] = 'http://www.google.com/'+self.connection_url
        env.globals['project_name'] =  os.getenv("PR_NAME")
        env.globals['user_name'] = os.getenv("NB_USER")
        env.globals['containername'] = os.getenv("HOSTNAME")


        # patch jinja env loading to modify page template
        def get_page(name):
            if name == 'tree.html':
                return tree_template
            if name == 'notebook.html':
                return notebook_template
            if name == 'terminal.html':
                return terminal_template
            if name == 'edit.html':
                return edit_template

        orig_loader = env.loader
        env.loader = ChoiceLoader([
            FunctionLoader(get_page),
            orig_loader,
        ])

     
      def init_webapp(self):

          super(KooplexUserNotebookApp,self).init_webapp()
          self.patch_templates()

def main(argv=None):
    return KooplexUserNotebookApp.launch_instance(argv)


if __name__ == "__main__":
     main()
