#!/usr/bin/env python
"""Extend regular notebook server to be aware of multiuser things."""

# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

from jinja2 import ChoiceLoader, FunctionLoader
from notebook.notebookapp import NotebookApp

page_template = """
{% extends "templates/page.html" %}
{% block logo %}
KOOPLEX
{% endblock %}
{% block header_buttons %}
<div class="navbar navbar-inverse navbar-fixed-top" style="padding: 5px 40px 5px 40px;">
  <div class="container-fluid">
    <div class="navbar-header">
        <a href="/hub/notebooks" class="navbar-brand">Kooplex Hub</a>
    </div>
    <ul class="nav navbar-nav">
     <li><a href="#"  class="navbar-brand">Report name: <strong>{{ report_name }}</strong></a></li>
     <li><a href="#"  class="navbar-brand">Author: <strong>{{ author_name }}</strong></a></li>
    </ul>
  </div>     <!-- container-fluid -->
</div>
{% endblock %}
{% block login_widget %}
{% endblock %}
{% block header %}
{% endblock %}
"""



class KooplexUserNotebookApp(NotebookApp):

      def patch_templates(self):
        import os

        # let us point to some crasy urls with the buttons
        # this illustrates the values of some internal url type strings
        env = self.web_app.settings['jinja2_env']
        env.globals['report_name'] =  os.getenv("REPORT_NAME")
        env.globals['author_name'] = os.getenv("AUTHOR NAME")


        # patch jinja env loading to modify page template
        def get_page(name):
            if name == 'page.html':
                return page_template

        orig_loader = env.loader
        env.loader = ChoiceLoader([
            FunctionLoader(get_page),
            orig_loader,
        ])

     
      def init_webapp(self):

          super(KooplexUserNotebookApp,self).init_webapp()
          self.patch_templates()

def main(argv=None):
    return KooplexUserNotebookApp.launch_instance(argv)


if __name__ == "__main__":
     main()
