apiVersion: v1
kind: ConfigMap
metadata:
  name: initscripts
  namespace: k8plex-test
data:
  nsswitch: |
          sed -i -e "s,passwd.*,passwd: ldap compat systemd," -e "s,group.*,group: ldap compat systemd," /etc/nsswitch.conf

  #/init/01-nslcd.sh
  nslcd: |
          #! /bin/bash
          
          # We cannot mount this config file into /etc because it is not empty
          if [ -f /etc/mnt/nslcd.conf ] ; then
            cat /etc/mnt/nslcd.conf > /etc/nslcd.conf
            chmod 0600 /etc/nslcd.conf
          fi
          
          service nslcd start
  #/init/02-usermod.sh
  usermod: |
          #!/bin/bash


          # Change UID of NB_USER to NB_UID if it does not match 
          if [ "$NB_UID" != $(id -u $NB_USER) ] ; then
             usermod -u $NB_UID $NB_USER
          fi

  pip: |
          pip install debugpy==1.5.1
  sshstart: |
          service ssh start
  runserver: |
          #! /bin/bash
        
          exec 2> /var/log/hub/runserver.log
          exec 1>&2
          
          ##FIXME: this is not nice
          #env > /var/spool/cron/crontabs/root
          #echo -e "*/1 * * * * /usr/bin/python3 /kooplexhub/kooplexhub/manage.py scheduler\n" >> /var/spool/cron/crontabs/root
          #/etc/init.d/cron start
          
          cd /kooplexhub/kooplexhub/
          #git pull
          
          
          while (true) ; do
            echo "Waiting for mysql server"
            mysql -u $HUBDB_USER --password=$HUBDB_PW -h $HUBDB_HOSTNAME $HUBDB -e "SELECT 1"
            [ $? = 0 ] && break
            sleep 2
          done
          
          /usr/bin/python3 manage.py runserver 0.0.0.0:80

