FROM ##PREFIX##-base
MAINTAINER Kooplex Team <kooplex@complex.elte.hu

RUN apt update && \
    apt install -y --no-install-recommends curl git ssh-client davfs2
RUN apt clean

RUN chmod u+s /usr/sbin/mount.davfs

COPY nsswitch.conf /etc
COPY nslcd.conf /etc
RUN chmod 600 /etc/nslcd.conf
COPY start.sh /init
COPY init-ssh-agent.sh /usr/local/bin
COPY patch-gitconfig.sh /usr/local/bin
COPY patch-davfs.sh /usr/local/bin
COPY share.sh /usr/local/bin
ADD create_admin.sh /create_admin.sh
RUN chmod 700 /create_admin.sh
