FROM ##PREFIX##-base
MAINTAINER Kooplex Team <kooplex@complex.elte.hu


#FIXME: inotify-tools and nsswitch, nslcd conf should be part of base
RUN apt update && \
    apt install -y --no-install-recommends curl git ssh-client davfs2 inotify-tools
RUN apt clean

## RUN chmod u+s /usr/sbin/mount.davfs

COPY nsswitch.conf /etc
COPY nslcd.conf /etc
RUN chmod 600 /etc/nslcd.conf
COPY start.sh /init
COPY 03-startinotify.sh /init
COPY init-ssh-agent.sh /usr/local/bin
RUN rmdir /home
RUN ln -s /mnt/.volumes/home /home
## COPY patch-gitconfig.sh /usr/local/bin
## COPY patch-davfs.sh /usr/local/bin
## COPY share.sh /usr/local/bin
## ADD create_admin.sh /create_admin.sh
## ADD create_user_userdb.sh /create_user_userdb.sh
## RUN chmod 700 /create_admin.sh
