FROM jupyter/scipy-notebook
USER root

RUN apt-get update
RUN apt-get install -y libncurses5-dev libncursesw5-dev zlib1g-dev
RUN mkdir /opt/samtools_sources
ADD samtools-1.3.tar.bz2 /opt/samtools_sources/samtools-1.3.tar.bz2
ADD bcftools-1.3.tar.bz2 /opt/samtools_sources/bcftools-1.3.tar.bz2
ADD htslib-1.3.tar.bz2 /opt/samtools_sources/htslib-1.3.tar.bz2
RUN mkdir /opt/samtools
RUN /opt/samtools_sources/samtools-1.3.tar.bz2/samtools-1.3/configure --prefix=/opt/samtools
RUN make -C /opt/samtools_sources/samtools-1.3.tar.bz2/samtools-1.3
RUN make -C /opt/samtools_sources/samtools-1.3.tar.bz2/samtools-1.3 install
RUN /opt/samtools_sources/htslib-1.3.tar.bz2/htslib-1.3/configure --prefix=/opt/samtools
RUN make -C /opt/samtools_sources/htslib-1.3.tar.bz2/htslib-1.3
RUN make -C /opt/samtools_sources/htslib-1.3.tar.bz2/htslib-1.3 install
RUN make -C /opt/samtools_sources/bcftools-1.3.tar.bz2/bcftools-1.3
RUN make -C /opt/samtools_sources/bcftools-1.3.tar.bz2/bcftools-1.3 prefix=/opt/samtools install
RUN mkdir /opt/bwa
ADD bwakit-0.7.12_x64-linux.tar.bz2 /opt/bwa/bwakit-0.7.12_x64-linux.tar.bz2
RUN mkdir /opt/blast
ADD ncbi-blast-2.2.31+-x64-linux.tar.gz /opt/blast/ncbi-blast-2.2.31+-x64-linux.tar.gz
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3 get-pip.py
RUN pip3 install numpy biopython ete3 geopy jinja2

RUN echo PATH=\"/opt/samtools/bin:/opt/blast/ncbi-blast-2.2.31+-x64-linux.tar.gz/ncbi-blast-2.2.31+/bin:/opt/bwa/bwakit-0.7.12_x64-linux.tar.bz2/bwa.kit:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\" > /etc/environment
RUN apt-get install -y openjdk-7-jdk
RUN apt-get install -y r-base libzmq3-dev
RUN mkdir /opt/GATK
ADD GenomeAnalysisTK.jar /opt/GATK/GenomeAnalysisTK.jar
ADD picard.jar /opt/GATK/picard.jar
ENV PATH "/opt/samtools/bin:/opt/blast/ncbi-blast-2.2.31+-x64-linux.tar.gz/ncbi-blast-2.2.31+/bin:/opt/bwa/bwakit-0.7.12_x64-linux.tar.bz2/bwa.kit:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
WORKDIR /home/jovyan/work/notebooks
COPY flu_pilot /home/jovyan/work/notebooks/
RUN chown -R jovyan:users /home/jovyan
ADD https://raw.githubusercontent.com/oroszl/koopi/master/koopi_singleuser.py /usr/local/bin/
RUN chown jovyan:users /usr/local/bin/koopi_singleuser.py
USER jovyan