apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-scratch 
  namespace: k8plex-test
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName:
    test-slurm-scratch
