FROM owncloud:latest

USER root

#ADD LDAP
RUN apt-get update ; exit 0
RUN apt-get install libldap2-dev

RUN a2enmod authnz_ldap
RUN ln -s /usr/lib/x86_64-linux-gnu/libldap.a /usr/lib/
RUN ln -s /usr/lib/x86_64-linux-gnu/libldap.so /usr/lib/
RUN docker-php-ext-configure ldap && docker-php-ext-install ldap

RUN service apache2 restart


RUN apt-get update; exit 0
RUN apt-get -y install pwauth members

RUN addgroup auth_cloud

RUN useradd -ms /bin/bash newuser -p newpass
RUN adduser newuser auth_cloud
USER newuser
WORKDIR /home/newuser


USER root
RUN useradd -ms /bin/bash olduser -p oldpass
RUN adduser olduser auth_cloud
USER olduser
WORKDIR /home/olduser


USER root
WORKDIR /var/www/html
COPY docker-entrypoint.sh /entrypoint.sh

#Ez nem mukodik
#RUN echo "jegesm\nalmafa137" > /vmi
#ADD user_pam  /var/www/html/
#RUN chgrp www_data -R /vmi /var/www/html/apps/user_pam
#USER www-data
#WORKDIR /var/www/html
#RUN /var/www/html/occ maintenance:install < /vmi
#RUN  su  /var/www/html/occ user_pam:enable

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get install -q -y \
    libnss-ldapd openldap-utils ldap-client libldap2-dev
# Do not run nslcd as a daemon
RUN systemctl disable nslcd   
RUN pam-auth-update --package 
 

#USER root
ENTRYPOINT ["/entrypoint.sh"]
CMD ["apache2-foreground"]
