---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-test-data
spec:
  capacity:
    storage: 50G
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/vols/k8plex_test/service/gitea
    server: veo1.krft
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data
  namespace: k8plex-test
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50G
  storageClassName: ""
  volumeName: gitea-test-data
