---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ldap-test
spec:
  capacity:
    storage: 1G
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/vols/k8plex_test/service/ldap
    server: veo1.krft
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-data
  namespace: k8plex-test
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1G
  storageClassName: ""
  volumeName: ldap-test
