FROM kooplex-base

MAINTAINER Laszlo Dobos <dobos@complex.elte.hu

# TODO add jupyter stuff

# Configure environment
ENV CONDA_VER "4.1.11"
ENV CONDA_DIR /opt/conda
ENV PATH $CONDA_DIR/bin:$PATH
ENV SHELL /bin/bash
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

# Create conda dir
RUN mkdir -p $CONDA_DIR
    
# Install conda
RUN cd /tmp && \
    mkdir -p $CONDA_DIR && \
    wget --quiet https://repo.continuum.io/miniconda/Miniconda3-$CONDA_VER-Linux-x86_64.sh && \
    # echo "9ea57c0fdf481acf89d816184f969b04bc44dea27b258c4e86b1e3a25ff26aa0 *Miniconda3-3.19.0-Linux-x86_64.sh" | sha256sum -c - && \
    /bin/bash Miniconda3-$CONDA_VER-Linux-x86_64.sh -f -b -p $CONDA_DIR && \
    rm Miniconda3-$CONDA_VER-Linux-x86_64.sh && \
    $CONDA_DIR/bin/conda install --quiet --yes conda && \
    $CONDA_DIR/bin/conda config --system --add channels conda-forge && \
    $CONDA_DIR/bin/conda install --quiet --yes 'jupyter_core==4.2' && \
    $CONDA_DIR/bin/conda install --quiet --yes 'notebook==4.2' && \
    $CONDA_DIR/bin/conda install --quiet --yes 'jupyterhub' 

# Install Jupyter notebook
# RUN conda clean -tipsy
    
# Install JupyterHub to get the jupyterhub-singleuser startup script
RUN pip install 'jupyter_dashboards' && \
    jupyter-dashboards quick-setup && \
    jupyter-nbextension enable jupyter_dashboards --py

RUN chmod a+rxw $CONDA_DIR


# Add local files as late as possible to avoid cache busting
ADD scripts/start-notebook.sh /usr/local/bin/start-notebook.sh
ADD scripts/start-singleuser.sh /usr/local/bin/start-singleuser.sh

