FROM ##PREFIX##-base

RUN apt update 

RUN apt install -y curl zip && \
    apt install --yes nodejs 

RUN apt install -y tmux  curlftpfs\
 liblapack-dev libblas-dev \
 gfortran libfreetype6* pkg-config \
 git gcc mpi-default-dev mpi-default-bin libfftw3-dev fftw3 cmake \
 inotify-tools \
 autoconf libncurses5-dev libncursesw5-dev zlib1g-dev libbz2-dev liblzma-dev apt-rdepends \
 libfontconfig1 libxrender1 libxrender-dev \
 g++-5 libicu-dev libxml2-dev \
 libblacs-mpi-dev libscalapack-mpi-dev \
 texlive-xetex texlive-lang-european texlive-science\
 libgtk2.0-0 build-essential \
    libssl-dev \
    uuid-dev \
    libgpgme11-dev \
    squashfs-tools \
    libseccomp-dev \
    pkg-config ssh



RUN rm -rf /var/lib/apt/lists/*

