FROM ##PREFIX##-base

RUN apt update 

RUN apt install -y curl && \
    curl -sL https://deb.nodesource.com/setup_10.x |  bash - && \
    apt install --yes nodejs 

RUN apt update 
RUN apt install -y tmux zip curlftpfs
RUN apt install -y liblapack-dev libblas-dev
RUN apt install -y gfortran libfreetype6* pkg-config
RUN apt install -y git gcc mpi-default-dev mpi-default-bin libfftw3-dev fftw3 cmake
RUN apt install -y inotify-tools
RUN apt install -y autoconf libncurses5-dev libncursesw5-dev zlib1g-dev libbz2-dev liblzma-dev apt-rdepends 
RUN apt install -y libfontconfig1 libxrender1 libxrender-dev
RUN apt install -y g++-5 libicu-dev libxml2-dev
RUN apt install -y libblacs-mpi-dev libscalapack-mpi-dev
RUN apt install -y texlive-xetex texlive-lang-european texlive-science

#RUN chmod u+s /usr/sbin/mount.davfs

# TODO add jupyter stuff
# Configure environment
ENV CONDA_VER "latest"
ENV CONDA_DIR /opt/conda
ENV PATH $CONDA_DIR/bin:$PATH
ENV SHELL /bin/bash
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

# Create conda dir
RUN mkdir -p $CONDA_DIR

# Maybe this one is not needed, since you can create conda envs into volumes
RUN chmod a+wrx $CONDA_DIR    

# Install conda
RUN cd /tmp && \
    mkdir -p $CONDA_DIR && \
    wget --quiet https://repo.anaconda.com/archive/Anaconda3-5.2.0-Linux-x86_64.sh && \
    # echo "09f53738b0cd3bb96f5b1bac488e5528df9906be2480fe61df40e0e0d19e3d48 *Anaconda3-5.2.0-Linux-x86_64.sh" | sha256sum -c - && \
    /bin/bash Anaconda3-5.2.0-Linux-x86_64.sh -f -b -p $CONDA_DIR && \
    rm Anaconda3-5.2.0-Linux-x86_64.sh

RUN /opt/conda/bin/conda update -y conda

# WE NEED THIS TO BE ABLE TO RUN NOTEBOOK-SERVER WITHOUT ANY EXTERNAL VOLUME/MODUL etc...
RUN $CONDA_DIR/bin/conda install --quiet --yes  jupyter_core jupyter_client jupyter_console 
RUN $CONDA_DIR/bin/conda install --quiet --yes  notebook widgetsnbextension
RUN  $CONDA_DIR/bin/conda install --quiet --yes -c conda-forge jupyter_dashboards && \
     jupyter dashboards quick-setup --sys-prefix
RUN  $CONDA_DIR/bin/conda install --quiet --yes -c conda-forge jupyter_cms && \
     jupyter cms quick-setup --sys-prefix

# TO SWITCH BETWEEN CONDA ENVS
RUN pip install environment_kernels

RUN  $CONDA_DIR/bin/conda install --quiet --yes -c conda-forge ipywidgets=7.0 traittypes
RUN  $CONDA_DIR/bin/conda install --quiet --yes -c conda-forge bqplot
RUN jupyter nbextension enable --py --sys-prefix widgetsnbextension

RUN $CONDA_DIR/bin/conda install -v --yes  -c conda-forge parso=0.1.0

RUN $CONDA_DIR/bin/conda install --quiet --yes -c damianavila82 rise pivottablejs
RUN $CONDA_DIR/bin/conda install --quiet --yes  -c conda-forge ipyleaflet folium
RUN $CONDA_DIR/bin/conda install --quiet --yes seaborn pandas
RUN $CONDA_DIR/bin/conda install --quiet --yes  -c conda-forge altair branca vega vincent 

RUN $CONDA_DIR/bin/conda update -y notebook
RUN $CONDA_DIR/bin/conda update -y jupyter_client

RUN $CONDA_DIR/bin/conda install --quiet --yes  -c conda-forge jupyterlab
RUN $CONDA_DIR/bin/conda install --quiet --yes nb_conda nb_conda_kernels

RUN $CONDA_DIR/bin/conda install -v --quiet --yes nodejs
RUN $CONDA_DIR/bin/conda install -v --quiet --yes networkx

RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager #@0.33
RUN pip install jupyterlab_latex && jupyter serverextension enable --sys-prefix jupyterlab_latex && jupyter labextension install @jupyterlab/latex
RUN jupyter labextension install @jupyterlab/github #@0.5

RUN jupyter labextension install jupyterlab_vim

#RUN jupyter labextension install jupyterlab_bokeh
# pip install jupyterlab-discovery
#jupyter labextension install @mflevine/jupyterlab_html
#jupyter labextension install knowledgelab

RUN $CONDA_DIR/bin/conda install --quiet --yes  -c conda-forge jupyter_nbextensions_configurator
RUN $CONDA_DIR/bin/conda install --quiet --yes  -c conda-forge jupyter_contrib_nbextensions
