FROM ##PREFIX##-base-conda


RUN  $CONDA_DIR/bin/conda install --quiet --yes  jupyter_core jupyter_client jupyter_console   notebook widgetsnbextension ipywidgets
RUN  $CONDA_DIR/bin/conda install --quiet --yes -c conda-forge jupyter_cms && \
     jupyter cms quick-setup --sys-prefix

# TO SWITCH BETWEEN CONDA ENVS
RUN pip install environment_kernels jupyterthemes

RUN $CONDA_DIR/bin/conda install --quiet --yes  -c conda-forge bqplot jupyter_nbextensions_configurator jupyter_contrib_nbextensions ipyleaflet folium\
      jupyter_kernel_gateway plotly tqdm shapely geopandas nodejs networkx seaborn pandas
RUN jupyter nbextension enable --py --sys-prefix widgetsnbextension
RUN $CONDA_DIR/bin/conda install -c anaconda --quiet --yes nb_conda nb_conda_kernels 

RUN $CONDA_DIR/bin/conda install --quiet --yes -c damianavila82 rise pivottablejs
RUN apt update && apt install -y libssl-dev
RUN conda install -c defaults -c conda-forge dash jupyterlab-dash   
RUN pip install jupyter_plotly_dash dash-auth
RUN pip install dash-bootstrap-components==0.8.3 dash-core-components==1.7.0  dash-renderer==1.2.3
RUN $CONDA_DIR/bin/conda install --quiet --yes -c pyviz holoviews bokeh holoviews geoviews hvplot panel

# Install BokehJS
RUN wget http://cdn.pydata.org/bokeh/release/bokeh-1.3.4.min.js && \
    wget http://cdn.pydata.org/bokeh/release/bokeh-widgets-1.3.4.min.js && \
    wget http://cdn.pydata.org/bokeh/release/bokeh-tables-1.3.4.min.js && \
    wget http://cdn.pydata.org/bokeh/release/bokeh-api-1.3.4.min.js

RUN pip install dash-bootstrap-components==0.8.3 dash-core-components==1.7.0  dash-renderer==1.2.3
RUN $CONDA_DIR/bin/conda install --quiet --yes  -c conda-forge pandas==1.0.1
