FROM ##PREFIX##-base-conda


#RUN  $CONDA_DIR/bin/conda install --quiet --yes  jupyter_core==4.4.0 jupyter_client==5.2.4 jupyter_console   notebook==5.7.4 widgetsnbextension==3.0.8 ipywidgets==7.0.5 
RUN  $CONDA_DIR/bin/conda install --quiet --yes  jupyter_core jupyter_client jupyter_console   notebook widgetsnbextension ipywidgets
#RUN  $CONDA_DIR/bin/conda install --quiet --yes -c conda-forge jupyter_dashboards && \
#     jupyter dashboards quick-setup --sys-prefix
RUN  $CONDA_DIR/bin/conda install --quiet --yes -c conda-forge jupyter_cms && \
     jupyter cms quick-setup --sys-prefix

# TO SWITCH BETWEEN CONDA ENVS
RUN pip install environment_kernels

RUN  $CONDA_DIR/bin/conda install --quiet --yes  -c conda-forge  bqplot #traittypes
RUN  $CONDA_DIR/bin/conda install --quiet --yes  -c conda-forge jupyter_nbextensions_configurator jupyter_contrib_nbextensions
RUN jupyter nbextension enable --py --sys-prefix widgetsnbextension
RUN $CONDA_DIR/bin/conda install -c anaconda --quiet --yes nb_conda nb_conda_kernels 
RUN $CONDA_DIR/bin/conda install --quiet --yes --override-channels -c conda-forge ipyleaflet folium 
RUN $CONDA_DIR/bin/conda install --quiet --yes nodejs networkx seaborn pandas tqdm
RUN $CONDA_DIR/bin/conda install --quiet --yes -c damianavila82 rise pivottablejs


RUN apt update
RUN apt-get install -y libgtk2.0-0
#RUN $CONDA_DIR/bin/conda install --quiet --yes "poppler<0.62"

RUN $CONDA_DIR/bin/conda install --quiet --yes --override-channels -c conda-forge jupyter_kernel_gateway #==2.1.0

##### RUN $CONDA_DIR/bin/conda install -c conda-forge -y ipyvolume==0.4.5 ipywebrtc==0.3.0  
#RUN $CONDA_DIR/bin/conda install -c conda-forge -y ipywidgets  

RUN $CONDA_DIR/bin/conda install -c conda-forge plotly

