FROM ##PREFIX##-base-conda

RUN sudo apt-get update && sudo apt-get install -y \
    build-essential \
    libssl-dev \
    uuid-dev \
    libgpgme11-dev \
    squashfs-tools \
    libseccomp-dev \
    pkg-config

ENV VERSION 1.11 
ENV OS linux
ENV ARCH amd64
RUN wget https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz && \
    sudo tar -C /usr/local -xzvf go$VERSION.$OS-$ARCH.tar.gz && \
    rm go$VERSION.$OS-$ARCH.tar.gz

RUN echo 'export GOPATH=${HOME}/go' >> ~/.bashrc && \
    echo 'export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin' >> ~/.bashrc # &&  source ~/.bashrc

ENV GOPATH ${HOME}/go
ENV PATH /usr/local/go/bin:${PATH}:${GOPATH}/bin
WORKDIR /opt

## Go dep for singularity > 3.0
RUN git clone https://github.com/golang/dep.git
RUN cp -r dep/cmd/dep/ /usr/local/go/src/
#
## or another tag or branch if you like 
ENV VERSION v3.0.3 
RUN git clone https://github.com/sylabs/singularity.git
RUN env 
# omit this command to install the latest bleeding edge code from master
RUN cd singularity && \
    git fetch && \
    git checkout $VERSION && \
    mkdir -p /usr/local/go/src/github.com/sylabs/ && \
    cd .. && \
    cp -r singularity /usr/local/go/src/github.com/sylabs/

WORKDIR /usr/local/go/src/github.com/sylabs/singularity
RUN  ./mconfig && cd builddir && make && make install

RUN useradd -ms /bin/bash aaa

