FROM ##PREFIX##-base-conda-extras

#RUN pip install jupyterlab-bokeh-server && jupyter labextension install jupyterlab-bokeh-server
RUN  jupyter labextension install @pyviz/jupyterlab_pyviz jupyterlab-dash

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - && echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list && \
   apt update && apt install yarn


