FROM ##PREFIX##-notebook-base

RUN apt update && \
    apt install -y curl && \
    curl --silent --location https://deb.nodesource.com/setup_0.12 | sudo bash - && \
    apt install --yes nodejs npm && \
    npm install -g bower

RUN apt install -y tmux zip curlftpfs
RUN apt install -y liblapack-dev libblas-dev
RUN apt install -y gfortran libfreetype6* pkg-config
RUN apt install -y git gcc mpi-default-dev mpi-default-bin libfftw3-dev fftw3 cmake
RUN apt install -y davfs2
RUN chmod u+s /usr/sbin/mount.davfs


# TODO add jupyter stuff
# Configure environment
ENV CONDA_VER "latest"
ENV CONDA_DIR /opt/conda
ENV PATH $CONDA_DIR/bin:$PATH
ENV SHELL /bin/bash
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

# Create conda dir
RUN mkdir -p $CONDA_DIR

# Maybe this one is not needed, since you can create conda envs into volumes
RUN chmod a+wrx $CONDA_DIR    


# Install conda
RUN cd /tmp && \
    mkdir -p $CONDA_DIR && \
    wget --quiet https://repo.continuum.io/miniconda/Miniconda3-$CONDA_VER-Linux-x86_64.sh && \
    # echo "9ea57c0fdf481acf89d816184f969b04bc44dea27b258c4e86b1e3a25ff26aa0 *Miniconda3-3.19.0-Linux-x86_64.sh" | sha256sum -c - && \
    /bin/bash Miniconda3-$CONDA_VER-Linux-x86_64.sh -f -b -p $CONDA_DIR && \
    rm Miniconda3-$CONDA_VER-Linux-x86_64.sh 

# WE NEED THIS TO BE ABLE TO RUN NOTEBOOK-SERVER WITHOUT ANY EXTERNAL VOLUME/MODUL etc...
RUN $CONDA_DIR/bin/conda install --quiet --yes  jupyter_core jupyter_client jupyter_console 
RUN $CONDA_DIR/bin/conda install --quiet --yes  notebook widgetsnbextension
RUN  $CONDA_DIR/bin/conda install --quiet --yes -c conda-forge jupyter_dashboards && \
     jupyter dashboards quick-setup --sys-prefix
RUN  $CONDA_DIR/bin/conda install --quiet --yes -c conda-forge jupyter_cms && \
     jupyter cms quick-setup --sys-prefix


# TO SWITCH BETWEEN CONDA ENVS
RUN pip install environment_kernels

RUN apt install -y autoconf libncurses5-dev libncursesw5-dev zlib1g-dev libbz2-dev liblzma-dev apt-rdepends 
 
RUN apt install -y libblacs-mpi-dev libscalapack-mpi-dev
 

RUN  $CONDA_DIR/bin/conda install --quiet --yes -c conda-forge ipywidgets=7.0 traittypes
RUN  $CONDA_DIR/bin/conda install --quiet --yes -c conda-forge bqplot
RUN jupyter nbextension enable --py --sys-prefix widgetsnbextension

RUN $CONDA_DIR/bin/conda install -v --yes  -c conda-forge parso=0.1.0


RUN $CONDA_DIR/bin/conda install --quiet --yes -c damianavila82 rise

RUN apt update
RUN apt install -y libfontconfig1 libxrender1 libxrender-dev
RUN apt install -y g++-5 libicu-dev libxml2-dev
RUN apt install -y octave

RUN $CONDA_DIR/bin/conda install --quiet --yes  -c conda-forge jupyterlab
RUN apt install -y gnuplot



# This one is not needed as long as it cannot discover conda envs outside of /opt/conda

RUN $CONDA_DIR/bin/conda install --quiet --yes nb_conda nb_conda_kernels

RUN $CONDA_DIR/bin/conda install --quiet --yes  -c conda-forge jupyter_nbextensions_configurator
RUN $CONDA_DIR/bin/conda install --quiet --yes  -c conda-forge jupyter_contrib_nbextensions

ADD jupyter-notebook-kooplex /opt/conda/bin/jupyter-notebook-kooplex 
RUN chmod a+x /opt/conda/bin/jupyter-notebook-kooplex
ADD jupyter-report-kooplex /opt/conda/bin/jupyter-report-kooplex 
RUN chmod a+x /opt/conda/bin/jupyter-report-kooplex

# Add local files as late as possible to avoid cache busting
ADD start-notebook.sh /usr/local/bin/start-notebook.sh
ADD start-report.sh /usr/local/bin/start-report.sh
ADD kooplex-logo.png /opt/conda/lib/python3.6/site-packages/notebook/static/base/images/kooplex-logo.png

########## add the rest
RUN mkdir -p /init
ADD 0.sh /init/0.sh
ADD 1.sh /init/1.sh
ADD jupyter_notebook_config.py /etc/jupyter_notebook_config.py
ADD jupyter_report_config.py /etc/jupyter_report_config.py
ADD nslcd.conf /etc/nslcd.conf
ADD ldap.conf /etc/ldap/ldap.conf
ADD nsswitch.conf /etc/nsswitch.conf



