apiVersion: batch/v1
kind: Job
metadata:
  name: compile-submitjobspy
  namespace: k8plex-test
spec:
  completions: 1
  parallelism: 1
  completionMode: Indexed
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: image-registry.vo.elte.hu/jupyter-basic-v4.0
        name: py3p8
        command: [ "bash", "-c"]
        args: 
          - pip install nuitka && cd /opt/job-tools/ && python -m nuitka --static-libpython=no submit_job.py --output-dir=buildjob3p8 -o job-submit-3.8 && setfacl -m g::rx job-submit-3.8
        volumeMounts:
          - mountPath: /opt/job-tools
            name: job-tools
      - image: image-registry.vo.elte.hu/jupyter-siesta-v4.0
        name: py3p9
        command: [ "bash", "-c"]
        args: 
          - pip install nuitka && cd /opt/job-tools/ && python -m nuitka --static-libpython=no submit_job.py --output-dir=buildjob3p9 -o job-submit-3.9 && setfacl -m g::rx job-submit-3.9
        volumeMounts:
          - mountPath: /opt/job-tools
            name: job-tools
      nodeSelector:
        kubernetes.io/hostname: future1
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
       - name: job-tools
         persistentVolumeClaim:
           claimName: job-tools
      nodeSelector:
        kubernetes.io/hostname: "future1"
  suspend: false
