FROM jupyter/scipy-notebook

WORKDIR /home/jovyan/work/notebooks
COPY . /home/jovyan/work/notebooks/

USER root

RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3 get-pip.py
RUN  pip3 install --upgrade pip
RUN pip3 install numpy biopython ete3 geopy jinja2

RUN pip3 install  ipykernel
#RUN python3 -m ipykernel install


RUN chown -R jovyan:users /home/jovyan
ADD https://raw.githubusercontent.com/oroszl/koopi/master/koopi_singleuser.py /usr/local/bin/
RUN chown jovyan:users /usr/local/bin/koopi_singleuser.py
RUN git clone https://github.com/python-visualization/folium.git
# TODO: the following is needed because we use previous version of folium in the notebook:
RUN cd folium; git checkout 4dede722bd5ff2e62052230e763384f5f19fddfb; python3 setup.py install; cd ..
RUN git clone git://github.com/matplotlib/matplotlib.git
RUN cd matplotlib; python2 setup.py install; cd ..
USER jovyan