{
 "title": "Node overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Resources veo1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"veo1\"}[$__rate_interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"veo1\"})\n)\n",
     "legendFormat": "cpu"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"veo1\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"veo1\"}",
     "legendFormat": "Memory free"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"veo1\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"veo1\"}",
     "legendFormat": "Memory buffer"
    },
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"veo1\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"veo1\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"veo1\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\", instance=\"veo1\"}\n)/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"veo1\"}\n",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "Disk I/O veo1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=\"veo1\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=\"veo1\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "Memory veo1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"veo1\"})/1024^3",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network Received veo1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"veo1\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"veo1\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"veo1\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Network Transmitted veo1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"veo1\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"veo1\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"veo1\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Resources veo2",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"veo2\"}[$__rate_interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"veo2\"})\n)\n",
     "legendFormat": "cpu"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"veo2\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"veo2\"}",
     "legendFormat": "Memory free"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"veo2\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"veo2\"}",
     "legendFormat": "Memory buffer"
    },
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"veo2\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"veo2\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"veo2\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\", instance=\"veo2\"}\n)/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"veo2\"}\n",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "Disk I/O veo2",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=\"veo2\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=\"veo2\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "Memory veo2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"veo2\"})/1024^3",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network Received veo2",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"veo2\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"veo2\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"veo2\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Network Transmitted veo2",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"veo2\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"veo2\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"veo2\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Resources onco1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"onco1\"}[$__rate_interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"onco1\"})\n)\n",
     "legendFormat": "cpu"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"onco1\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"onco1\"}",
     "legendFormat": "Memory free"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"onco1\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"onco1\"}",
     "legendFormat": "Memory buffer"
    },
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"onco1\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"onco1\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"onco1\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\", instance=\"onco1\"}\n)/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"onco1\"}\n",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "Disk I/O onco1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=\"onco1\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=\"onco1\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "Memory onco1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"onco1\"})/1024^3",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network Received onco1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"onco1\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"onco1\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"onco1\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Network Transmitted onco1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"onco1\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"onco1\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"onco1\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Resources kubelet1-onco2",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet1-onco2\"}[$__rate_interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet1-onco2\"})\n)\n",
     "legendFormat": "cpu"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet1-onco2\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet1-onco2\"}",
     "legendFormat": "Memory free"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet1-onco2\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet1-onco2\"}",
     "legendFormat": "Memory buffer"
    },
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet1-onco2\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet1-onco2\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet1-onco2\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\", instance=\"kubelet1-onco2\"}\n)/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet1-onco2\"}\n",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "Disk I/O kubelet1-onco2",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=\"kubelet1-onco2\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=\"kubelet1-onco2\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "Memory kubelet1-onco2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"kubelet1-onco2\"})/1024^3",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network Received kubelet1-onco2",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet1-onco2\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet1-onco2\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet1-onco2\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Network Transmitted kubelet1-onco2",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet1-onco2\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet1-onco2\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet1-onco2\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Resources kubelet2-onco2",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet2-onco2\"}[$__rate_interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet2-onco2\"})\n)\n",
     "legendFormat": "cpu"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet2-onco2\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet2-onco2\"}",
     "legendFormat": "Memory free"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet2-onco2\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet2-onco2\"}",
     "legendFormat": "Memory buffer"
    },
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet2-onco2\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet2-onco2\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet2-onco2\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\", instance=\"kubelet2-onco2\"}\n)/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet2-onco2\"}\n",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "Disk I/O kubelet2-onco2",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=\"kubelet2-onco2\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=\"kubelet2-onco2\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "Memory kubelet2-onco2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"kubelet2-onco2\"})/1024^3",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network Received kubelet2-onco2",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet2-onco2\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet2-onco2\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet2-onco2\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Network Transmitted kubelet2-onco2",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet2-onco2\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet2-onco2\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet2-onco2\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Resources future1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"future1\"}[$__rate_interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"future1\"})\n)\n",
     "legendFormat": "cpu"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"future1\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"future1\"}",
     "legendFormat": "Memory free"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"future1\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"future1\"}",
     "legendFormat": "Memory buffer"
    },
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"future1\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"future1\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"future1\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\", instance=\"future1\"}\n)/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"future1\"}\n",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "Disk I/O future1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=\"future1\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=\"future1\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "Memory future1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"future1\"})/1024^3",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network Received future1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"future1\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"future1\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"future1\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Network Transmitted future1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"future1\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"future1\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"future1\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Resources atys",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"atys\"}[$__rate_interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"atys\"})\n)\n",
     "legendFormat": "cpu"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"atys\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"atys\"}",
     "legendFormat": "Memory free"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"atys\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"atys\"}",
     "legendFormat": "Memory buffer"
    },
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"atys\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"atys\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"atys\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\", instance=\"atys\"}\n)/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"atys\"}\n",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "Disk I/O atys",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=\"atys\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=\"atys\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "Memory atys",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"atys\"})/1024^3",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network Received atys",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"atys\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"atys\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"atys\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Network Transmitted atys",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"atys\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"atys\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"atys\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Resources kubelet1-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet1-fiek-cn3\"}[$__rate_interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet1-fiek-cn3\"})\n)\n",
     "legendFormat": "cpu"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet1-fiek-cn3\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet1-fiek-cn3\"}",
     "legendFormat": "Memory free"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet1-fiek-cn3\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet1-fiek-cn3\"}",
     "legendFormat": "Memory buffer"
    },
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet1-fiek-cn3\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet1-fiek-cn3\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet1-fiek-cn3\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\", instance=\"kubelet1-fiek-cn3\"}\n)/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet1-fiek-cn3\"}\n",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "Disk I/O kubelet1-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=\"kubelet1-fiek-cn3\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=\"kubelet1-fiek-cn3\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "Memory kubelet1-fiek-cn3",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"kubelet1-fiek-cn3\"})/1024^3",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network Received kubelet1-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet1-fiek-cn3\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet1-fiek-cn3\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet1-fiek-cn3\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Network Transmitted kubelet1-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet1-fiek-cn3\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet1-fiek-cn3\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet1-fiek-cn3\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Resources kubelet2-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet2-fiek-cn3\"}[$__rate_interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet2-fiek-cn3\"})\n)\n",
     "legendFormat": "cpu"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet2-fiek-cn3\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet2-fiek-cn3\"}",
     "legendFormat": "Memory free"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet2-fiek-cn3\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet2-fiek-cn3\"}",
     "legendFormat": "Memory buffer"
    },
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet2-fiek-cn3\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet2-fiek-cn3\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet2-fiek-cn3\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\", instance=\"kubelet2-fiek-cn3\"}\n)/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet2-fiek-cn3\"}\n",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "Disk I/O kubelet2-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=\"kubelet2-fiek-cn3\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=\"kubelet2-fiek-cn3\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "Memory kubelet2-fiek-cn3",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"kubelet2-fiek-cn3\"})/1024^3",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network Received kubelet2-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet2-fiek-cn3\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet2-fiek-cn3\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet2-fiek-cn3\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Network Transmitted kubelet2-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet2-fiek-cn3\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet2-fiek-cn3\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet2-fiek-cn3\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Resources kubelet3-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet3-fiek-cn3\"}[$__rate_interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet3-fiek-cn3\"})\n)\n",
     "legendFormat": "cpu"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet3-fiek-cn3\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet3-fiek-cn3\"}",
     "legendFormat": "Memory free"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet3-fiek-cn3\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet3-fiek-cn3\"}",
     "legendFormat": "Memory buffer"
    },
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet3-fiek-cn3\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet3-fiek-cn3\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet3-fiek-cn3\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\", instance=\"kubelet3-fiek-cn3\"}\n)/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet3-fiek-cn3\"}\n",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "Disk I/O kubelet3-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=\"kubelet3-fiek-cn3\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=\"kubelet3-fiek-cn3\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "Memory kubelet3-fiek-cn3",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"kubelet3-fiek-cn3\"})/1024^3",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network Received kubelet3-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet3-fiek-cn3\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet3-fiek-cn3\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet3-fiek-cn3\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Network Transmitted kubelet3-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet3-fiek-cn3\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet3-fiek-cn3\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet3-fiek-cn3\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Resources kubelet4-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet4-fiek-cn3\"}[$__rate_interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet4-fiek-cn3\"})\n)\n",
     "legendFormat": "cpu"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet4-fiek-cn3\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet4-fiek-cn3\"}",
     "legendFormat": "Memory free"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet4-fiek-cn3\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet4-fiek-cn3\"}",
     "legendFormat": "Memory buffer"
    },
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet4-fiek-cn3\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet4-fiek-cn3\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet4-fiek-cn3\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\", instance=\"kubelet4-fiek-cn3\"}\n)/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet4-fiek-cn3\"}\n",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "Disk I/O kubelet4-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 70 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=\"kubelet4-fiek-cn3\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=\"kubelet4-fiek-cn3\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "Memory kubelet4-fiek-cn3",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"kubelet4-fiek-cn3\"})/1024^3",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network Received kubelet4-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 70 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet4-fiek-cn3\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet4-fiek-cn3\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet4-fiek-cn3\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Network Transmitted kubelet4-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 70 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet4-fiek-cn3\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet4-fiek-cn3\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet4-fiek-cn3\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Resources kubelet5-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet5-fiek-cn3\"}[$__rate_interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet5-fiek-cn3\"})\n)\n",
     "legendFormat": "cpu"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet5-fiek-cn3\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet5-fiek-cn3\"}",
     "legendFormat": "Memory free"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet5-fiek-cn3\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet5-fiek-cn3\"}",
     "legendFormat": "Memory buffer"
    },
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet5-fiek-cn3\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet5-fiek-cn3\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet5-fiek-cn3\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\", instance=\"kubelet5-fiek-cn3\"}\n)/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet5-fiek-cn3\"}\n",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "Disk I/O kubelet5-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 77 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=\"kubelet5-fiek-cn3\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=\"kubelet5-fiek-cn3\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "Memory kubelet5-fiek-cn3",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"kubelet5-fiek-cn3\"})/1024^3",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network Received kubelet5-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 77 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet5-fiek-cn3\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet5-fiek-cn3\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet5-fiek-cn3\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Network Transmitted kubelet5-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 77 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet5-fiek-cn3\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet5-fiek-cn3\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet5-fiek-cn3\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Resources kubelet6-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet6-fiek-cn3\"}[$__rate_interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet6-fiek-cn3\"})\n)\n",
     "legendFormat": "cpu"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet6-fiek-cn3\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet6-fiek-cn3\"}",
     "legendFormat": "Memory free"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet6-fiek-cn3\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet6-fiek-cn3\"}",
     "legendFormat": "Memory buffer"
    },
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet6-fiek-cn3\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet6-fiek-cn3\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet6-fiek-cn3\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\", instance=\"kubelet6-fiek-cn3\"}\n)/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet6-fiek-cn3\"}\n",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "Disk I/O kubelet6-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 84 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=\"kubelet6-fiek-cn3\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=\"kubelet6-fiek-cn3\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "Memory kubelet6-fiek-cn3",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"kubelet6-fiek-cn3\"})/1024^3",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network Received kubelet6-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 84 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet6-fiek-cn3\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet6-fiek-cn3\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet6-fiek-cn3\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Network Transmitted kubelet6-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 84 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet6-fiek-cn3\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet6-fiek-cn3\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet6-fiek-cn3\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Resources kubelet7-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet7-fiek-cn3\"}[$__rate_interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet7-fiek-cn3\"})\n)\n",
     "legendFormat": "cpu"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet7-fiek-cn3\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet7-fiek-cn3\"}",
     "legendFormat": "Memory free"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet7-fiek-cn3\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet7-fiek-cn3\"}",
     "legendFormat": "Memory buffer"
    },
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet7-fiek-cn3\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet7-fiek-cn3\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet7-fiek-cn3\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\", instance=\"kubelet7-fiek-cn3\"}\n)/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet7-fiek-cn3\"}\n",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "Disk I/O kubelet7-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 91 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=\"kubelet7-fiek-cn3\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=\"kubelet7-fiek-cn3\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "Memory kubelet7-fiek-cn3",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"kubelet7-fiek-cn3\"})/1024^3",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network Received kubelet7-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 91 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet7-fiek-cn3\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet7-fiek-cn3\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet7-fiek-cn3\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Network Transmitted kubelet7-fiek-cn3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 91 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet7-fiek-cn3\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet7-fiek-cn3\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet7-fiek-cn3\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Resources kubelet1-fiek-cn4",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet1-fiek-cn4\"}[$__rate_interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet1-fiek-cn4\"})\n)\n",
     "legendFormat": "cpu"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet1-fiek-cn4\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet1-fiek-cn4\"}",
     "legendFormat": "Memory free"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet1-fiek-cn4\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet1-fiek-cn4\"}",
     "legendFormat": "Memory buffer"
    },
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet1-fiek-cn4\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet1-fiek-cn4\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet1-fiek-cn4\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\", instance=\"kubelet1-fiek-cn4\"}\n)/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet1-fiek-cn4\"}\n",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "Disk I/O kubelet1-fiek-cn4",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 98 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=\"kubelet1-fiek-cn4\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=\"kubelet1-fiek-cn4\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "Memory kubelet1-fiek-cn4",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"kubelet1-fiek-cn4\"})/1024^3",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network Received kubelet1-fiek-cn4",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 98 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet1-fiek-cn4\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet1-fiek-cn4\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet1-fiek-cn4\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Network Transmitted kubelet1-fiek-cn4",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 98 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet1-fiek-cn4\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet1-fiek-cn4\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet1-fiek-cn4\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Resources kubelet3-fiek-cn4",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet3-fiek-cn4\"}[$__rate_interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet3-fiek-cn4\"})\n)\n",
     "legendFormat": "cpu"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet3-fiek-cn4\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet3-fiek-cn4\"}",
     "legendFormat": "Memory free"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet3-fiek-cn4\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet3-fiek-cn4\"}",
     "legendFormat": "Memory buffer"
    },
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet3-fiek-cn4\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet3-fiek-cn4\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet3-fiek-cn4\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\", instance=\"kubelet3-fiek-cn4\"}\n)/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet3-fiek-cn4\"}\n",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "Disk I/O kubelet3-fiek-cn4",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 105 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=\"kubelet3-fiek-cn4\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=\"kubelet3-fiek-cn4\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "Memory kubelet3-fiek-cn4",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"kubelet3-fiek-cn4\"})/1024^3",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network Received kubelet3-fiek-cn4",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 105 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet3-fiek-cn4\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet3-fiek-cn4\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet3-fiek-cn4\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Network Transmitted kubelet3-fiek-cn4",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 105 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet3-fiek-cn4\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet3-fiek-cn4\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet3-fiek-cn4\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Resources kubelet4-fiek-cn4",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet4-fiek-cn4\"}[$__rate_interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"kubelet4-fiek-cn4\"})\n)\n",
     "legendFormat": "cpu"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet4-fiek-cn4\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet4-fiek-cn4\"}",
     "legendFormat": "Memory free"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet4-fiek-cn4\"}/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet4-fiek-cn4\"}",
     "legendFormat": "Memory buffer"
    },
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet4-fiek-cn4\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"kubelet4-fiek-cn4\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"kubelet4-fiek-cn4\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\", instance=\"kubelet4-fiek-cn4\"}\n)/node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"kubelet4-fiek-cn4\"}\n",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "Disk I/O kubelet4-fiek-cn4",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 112 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=\"kubelet4-fiek-cn4\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=\"kubelet4-fiek-cn4\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__rate_interval]))",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "Memory kubelet4-fiek-cn4",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"kubelet4-fiek-cn4\"})/1024^3",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network Received kubelet4-fiek-cn4",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 112 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet4-fiek-cn4\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet4-fiek-cn4\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"kubelet4-fiek-cn4\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  },
  {
   "title": "Network Transmitted kubelet4-fiek-cn4",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 112 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet4-fiek-cn4\", device=\"storageLAN\"}[$__rate_interval])",
     "legendFormat": "storageLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet4-fiek-cn4\", device=\"krftLAN\"}[$__rate_interval])",
     "legendFormat": "krftLAN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"kubelet4-fiek-cn4\", device=\"complexLAN\"}[$__rate_interval])",
     "legendFormat": "complexLAN"
    }
   ]
  }
 ]
}