#!/bin/bash

case "$REPORT_TYPE" in
    "bokeh")
        echo "Starting Report Bokeh Server"
        nice -n 19 /usr/local/bin/preview-bokeh.sh $REPORT_DIR
    ;;
    "service")
        echo "Starting Report KernelGateway Server"
        cd $REPORT_DIR
        nice -n 19 /usr/local/bin/preview-nb-api.sh $REPORT_INDEX
    ;;
    "dynamic")
        echo "Starting Notebook Server"
        cd $REPORT_DIR
        echo "Trust notebook"
        jupyter trust $REPORT_INDEX
        nice -n 19 /usr/local/bin/start-notebook.sh --config=/etc/jupyter_report_config.py --NotebookApp.base_url="/${NB_URL}" --NotebookApp.port=$NB_PORT --NotebookApp.token=$NB_TOKEN --notebook-dir=$REPORT_DIR
    ;;
    *)
        echo "Starting notebook for $NB_USER..."
        nice -n 19 /usr/local/bin/start-notebook.sh --config=/etc/jupyter_notebook_config.py --NotebookApp.base_url=$NB_URL --NotebookApp.port=$NB_PORT --NotebookApp.token=$NB_TOKEN --EnvironmentKernelSpecManager.display_name_template=\" {}\"
    ;;
esac

echo "Should not reach this point"
