FROM gitlab/gitlab-ce:10.1.2-ce.0

ADD nginx-gitlab-http.conf.erb /opt/gitlab/embedded/cookbooks/gitlab/templates/default/nginx-gitlab-http.conf.erb
ADD gitlab.rb /etc/gitlab/gitlab.rb
ADD make_admin.sh /make_admin.sh
RUN chmod 700 /make_admin.sh 
