apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: k8plex-test
spec:
  selector:
    app: proxy
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: api
      protocol: TCP
      port: 8001
      targetPort: 8001
