FROM rocker/verse

USER root

# configure apt frontent
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -yq --no-install-recommends \
    wget \
    bzip2 \
    ca-certificates \
    sudo vim\
    locales

RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen

# Install Tini
RUN wget --quiet https://github.com/krallin/tini/releases/download/v0.9.0/tini && \
    echo "faafbfb5b079303691a939a747d7f60591f2143164093727e870b289a44d9872 *tini" | sha256sum -c - && \
    mv tini /usr/local/bin/tini && \
    chmod +x /usr/local/bin/tini

# Install LDAP and setup authentication
RUN touch /etc/nslcd.conf && \
    chmod 0600 /etc/nslcd.conf

RUN apt-get install -q -y libnss-ldapd openldap-utils ldap-client libldap2-dev 


RUN ln -s /usr/lib/x86_64-linux-gnu/libldap.a /usr/lib/  
RUN ln -s /usr/lib/x86_64-linux-gnu/libldap.so /usr/lib/  

RUN apt update
RUN apt install --yes systemd
# Do not run nslcd as a daemon
RUN systemctl disable nslcd


RUN pam-auth-update --package

# Install NFS client ACL manipulation
RUN apt-get install -q -y nfs-common acl nfs4-acl-tools
RUN apt install -y nginx
    
# Patch bashrc
COPY bashrc_tail /tmp
RUN cat /tmp/bashrc_tail >> /etc/bash.bashrc
RUN rm /tmp/bashrc_tail

EXPOSE 111/udp

#RUN mkdir /init

# we don't run apt-get clean, coz the apt-cache is useful when preparing new module volumes
RUN rm -rf /var/lib/apt/lists/*

ENV SSH_AUTH_SOCK /tmp/my_sshagent_sock

RUN mv /init /init.sh

ENV PASSWORD rstudio 
ADD entrypoint-rstudio.sh /entrypoint.sh
ADD rserver.conf /etc/rstudio/rserver.conf
ADD rstudio-nginx.conf /etc/nginx/sites-enabled/
ADD rstudio-login.html /etc/rstudio/login.html
RUN chmod a-w /etc/rstudio/login.html

#Meg valamit ezzel is kezdeni kell /var/run/s6/services/rstudio/run

ENTRYPOINT ["tini", "--"]
CMD ["/bin/bash", "/entrypoint.sh"]

