apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ldap
  namespace: k8plex-test
spec:
  serviceName: ldap-test
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app:  ldap
    spec:
      containers:
      - image: osixia/openldap:1.5.0
        name: ldap
        #command: [ 'sleep', 'infinity' ]
        command: ["/container/tool/run", "--dont-touch-etc-hosts"]
        ports:
          - containerPort: 389
            name: ldap
        volumeMounts:
          - mountPath: /var/log/ldap
            name: svc
            subPath: log
          - mountPath: /var/lib/ldap
            name: svc
            subPath: db
          - mountPath: /usr/local/ldap
            name: svc
            subPath: helper
          - mountPath: /etc/ldap/slapd.d
            name: svc
            subPath: slapd.d
        env:
          - name: LDAP_ORGANISATION
            value: "kooplex organization"
          - name: LDAP_DOMAIN
            value: "k8plex-test.vo.elte.hu"
          - name: LDAP_ADMIN_PASSWORD
            value: "pimPALA2021"
     # nodeSelector:
     #   kubernetes.io/hostname: veo1
      volumes:
        - name: svc
          persistentVolumeClaim:
            claimName: ldap-data
