apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oauth-data
  namespace: k8plex-test
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: oauth-test
