FROM nginx

# configure apt frontent
ENV DEBIAN_FRONTEND noninteractive

RUN apt update
RUN apt install --no-install-recommends -y php7.0 php7.0-mysql php7.0-fpm php7.0-curl nginx-full vim less php7.0-dom php7.0-xml
RUN apt install -y openssl ca-certificates

## FIXME
RUN echo "postfix postfix/mailname string ##OUTERHOST##" | debconf-set-selections && \
    echo  "postfix postfix/main_mailer_type string 'Satellite system'" | debconf-set-selections &&\
    echo  "postfix postfix/relayhost string '##MAIL_SERVER_HOSTNAME##'" | debconf-set-selections &&\
    apt install -y postfix


RUN mkdir -p /srv/
#ADD src/consent  /srv/consent

COPY database.php /srv/consent/application/config/database.php
 
COPY nginx.conf /etc/nginx/ 
COPY sites.conf /etc/nginx/

ADD hydraconsent-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh


ENTRYPOINT ["/entrypoint.sh"]

