FROM nginx

RUN apt update
RUN apt install --no-install-recommends -y php7.0 php7.0-mysql php7.0-fpm php7.0-curl nginx-full vim less

RUN mkdir -p /srv/
#ADD src/consent  /srv/consent

COPY database.php /srv/consent/application/config/database.php
 
COPY nginx.conf /etc/nginx/ 
COPY sites.conf /etc/nginx/

ADD hydraconsent-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh


ENTRYPOINT ["/entrypoint.sh"]

