FROM ##PREFIX##-base-for-notebooks

######################################################################
# Data mining extra
######################################################################
RUN $CONDA_DIR/bin/conda install  --quiet --yes -c conda-forge xgboost
RUN $CONDA_DIR/bin/conda install  --quiet --yes tensorflow keras opencv  h5py  #graphviz 
#RUN $CONDA_DIR/bin/conda update --prefix /opt/conda anaconda

RUN pip install graphviz 
######################################################################


