FROM nginx

RUN apt update && apt install -y  vim iputils-ping
RUN install -y python3 python3-pip
RUN pip3 install flask, flask_httpauth

EXPOSE 80
EXPOSE 443
EXPOSE 5000

COPY 01-api-start.sh /init
RUN chmod +x /init/02-api-start.sh
RUN mkdir /local
COPY api.py /local


#COPY outerhost.conf /etc/nginx/conf.d/outerhost.conf 
#COPY ##PREFIX##.crt  /etc/nginx/keys/##PREFIX##.crt
#COPY ##PREFIX##.key  /etc/nginx/keys/##PREFIX##.key
#COPY custom_502.html /usr/share/nginx/html/custom_502.html 
##COPY custom_404.html /usr/share/nginx/html/custom_404.html 
