FROM ##PREFIX##-base

RUN apt update && apt install -y ssh docker.io
RUN ssh-keygen -P ""  -f /root/.ssh/id_rsa


ADD entrypoint.sh /entrypoint.sh
RUN chmod a+x entrypoint.sh


CMD ["sleep","10000"]
#CMD ["/entrypoint.sh"]
